version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hills-draw-calendar"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-epve62ugfhu2"
s3_prefix = "hills-draw-calendar"
region = "ap-southeast-2"
profile = "df"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
